config:
  - key: config/services/proxy.edge/ui/color
    value: light-blue

  - key: config/services/proxy.edge/ui/title
    value: ""

  - key: config/services/proxy.edge/statsd/rules
    file: proxy.edge_statsd_rules.txt
